/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/activity/detail" |
       "/pages/activity/list" |
       "/pages/booking/confirm" |
       "/pages/booking/courseDetail" |
       "/pages/booking/index" |
       "/pages/card/courseDetail" |
       "/pages/card/detail" |
       "/pages/card/list" |
       "/pages/coach/detail" |
       "/pages/coach/list" |
       "/pages/index/qrcode" |
       "/pages/store/detail" |
       "/pages/store/list" |
       "/pages/user/login" |
       "/pages/user/my" |
       "/pages/user/profile";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/booking/index" | "/pages/user/my"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
